# Generated by Django 4.0.3 on 2022-05-22 22:43

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.core.validators
from django.core.management import call_command
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import venue.models


def upload_data(apps, schema_editor):
    call_command("loaddata", "./fixtures/venue_initial_data.json")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitchenType', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=512)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', keep_meta=True, null=True, quality=-1, size=[500, 300], upload_to=venue.models.venue_image_upload)),
                ('deliveryArea', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('deliveryCost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('deliveryMinimalOrderPrice', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('zipCode', models.CharField(max_length=6)),
                ('street', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('kitchenType', models.ManyToManyField(to='venue.kitchentype')),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venues', to='menu.menu')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VenueRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.CharField(blank=True, max_length=512)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='venueRatings', to='venue.venue')),
            ],
        ),
        migrations.CreateModel(
            name='VenueBusinessTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekDay', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('openHour', models.TimeField(null=True)),
                ('closeHour', models.TimeField(null=True)),
                ('venue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='openingHours', to='venue.venue')),
            ],
        ),
        migrations.CreateModel(
            name='UserFavoriteVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='favorite_by', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='favorite_venues', to='venue.venue')),
            ],
        ),
        migrations.RunPython(upload_data)
    ]
