# Generated by Django 4.0.3 on 2022-05-22 22:43

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import menu.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, verbose_name='menu name')),
                ('description', models.CharField(blank=True, help_text='Any additional text that the menu might need, i.e. Served between 11:00am and 4:00pm.', max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='menu category name')),
                ('description', models.CharField(blank=True, help_text="The additional text is any bit of related information to go along with a menu category, i.e. the 'Pasta' category might have details that say 'All entrees come with salad and bread'.", max_length=128, null=True)),
                ('sequence', models.IntegerField(default=0, help_text='The order is the order that this category should appear in when rendered on the templates.')),
                ('menu', models.ForeignKey(blank=True, help_text="The menus that this category belongs to, i.e. 'Lunch'.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='menu.menu')),
            ],
            options={
                'verbose_name': 'menu category',
                'verbose_name_plural': 'menu categories',
                'ordering': ['sequence', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the item on the menu.', max_length=48)),
                ('description', models.CharField(blank=True, help_text='The description is a simple text description of the menu item.', max_length=128, null=True)),
                ('sequence', models.IntegerField(default=0, help_text='The order is to specify the order in which items show up on the menu.', verbose_name='sequence')),
                ('price', models.IntegerField(help_text='The price is the cost of the item.')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', keep_meta=True, null=True, quality=-1, size=[150, 150], upload_to=menu.models.menu_item_image_upload)),
                ('category', models.ForeignKey(blank=True, help_text="Category is the menu category that this menu item belongs to, i.e. 'Appetizers'.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.menucategory', verbose_name='menu category')),
            ],
            options={
                'verbose_name': 'menu item',
                'verbose_name_plural': 'menu items',
                'ordering': ['category', 'sequence', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the item on the menu.', max_length=48)),
                ('description', models.CharField(blank=True, help_text='The description is a simple text description of the menu addon.', max_length=128, null=True)),
                ('sequence', models.IntegerField(default=0, help_text='The order is to specify the order in which items show up on the menu.', verbose_name='sequence')),
                ('price', models.IntegerField(help_text='The price is the cost of the item.')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', keep_meta=True, null=True, quality=-1, size=[150, 150], upload_to=menu.models.menu_addon_image_upload)),
                ('item', models.ForeignKey(blank=True, help_text="Addon is the Item category that this menu item belongs to, i.e. 'Appetizers'.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='menu.menuitem', verbose_name='menu item')),
            ],
            options={
                'verbose_name': 'menu addon',
                'verbose_name_plural': 'menu addons',
                'ordering': ['item', 'sequence', 'name'],
            },
        ),
    ]
